server {
<<<<<<< HEAD
    listen 7000;  # Change to port 7000
    server_name localhost;

    root /usr/share/nginx/html;  # Path to the app's build output
    index index.html;

    # For handling SPAs (Single Page Apps like React, Angular, etc.)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: logging
    #    access_log /var/log/nginx/access.log;
    #    error_log /var/log/nginx/error.log;

    # Optional: Custom 404 error page handling
    error_page 404 /404.html;
    location = /404.html {
=======
    listen 7000;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
>>>>>>> ce02ed1 (added nginx config)
        root /usr/share/nginx/html;
    }
}
