name: Deploy Coffe FE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/coffeshop || exit

            echo "Pull latest code"
            git pull origin main

            echo "Stop old container"
            docker ps -aq --filter "name=coffe_fe" | grep -q . && docker stop coffe_fe && docker rm -f coffe_fe || true

            echo "Remove old image"
            docker rmi coffe_fe:v1 || true

            echo "Build new image"
            docker build --no-cache -t coffe_fe:v1 .

            echo "Run container"
            sudo docker run -d --restart always --name coffe_fe -p 7001:7000 coffe_fe:v1
